import { NextResponse } from "next/server"
import { requireAdmin } from "@/lib/supabase/admin-server"

const TABLES={services:"body_services",categories:"service_categories",bookings:"service_bookings",reviews:"service_reviews",gallery:"service_gallery"} as const
type Resource=keyof typeof TABLES
function tableFor(resource:string){return TABLES[resource as Resource]}
export async function GET(_request:Request,{params}:{params:Promise<{resource:string}>}){const {resource}=await params,table=tableFor(resource),admin=await requireAdmin();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});if(!table)return NextResponse.json({error:"Unknown resource"},{status:404});const orderColumn=resource==="bookings"||resource==="reviews"?"created_at":"sort_order";const {data,error}=await admin.service.from(table).select("*").order(orderColumn,{ascending:resource!=="bookings"&&resource!=="reviews"});return error?NextResponse.json({error:error.message},{status:500}):NextResponse.json({data:data??[]})}
export async function POST(request:Request,{params}:{params:Promise<{resource:string}>}){const {resource}=await params,table=tableFor(resource),admin=await requireAdmin();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});if(!table)return NextResponse.json({error:"Unknown resource"},{status:404});const body=await request.json();delete body.id;delete body.created_at;delete body.updated_at;const {data,error}=await admin.service.from(table).insert(body).select().single();return error?NextResponse.json({error:error.message},{status:422}):NextResponse.json({data},{status:201})}
export async function PATCH(request:Request,{params}:{params:Promise<{resource:string}>}){const {resource}=await params,table=tableFor(resource),admin=await requireAdmin();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});if(!table)return NextResponse.json({error:"Unknown resource"},{status:404});const body=await request.json(),id=body.id;if(!id)return NextResponse.json({error:"Missing id"},{status:400});delete body.id;delete body.created_at;body.updated_at=new Date().toISOString();const {data,error}=await admin.service.from(table).update(body).eq("id",id).select().single();return error?NextResponse.json({error:error.message},{status:422}):NextResponse.json({data})}
export async function DELETE(request:Request,{params}:{params:Promise<{resource:string}>}){const {resource}=await params,table=tableFor(resource),admin=await requireAdmin();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});if(!table)return NextResponse.json({error:"Unknown resource"},{status:404});const id=new URL(request.url).searchParams.get("id");if(!id)return NextResponse.json({error:"Missing id"},{status:400});const {error}=await admin.service.from(table).delete().eq("id",id);return error?NextResponse.json({error:error.message},{status:422}):NextResponse.json({ok:true})}
