// Mock data — replaceable once the backend is connected.
// Keep the shape identical to what the real API will return.

import type { DoctorPlan, Meal, Product, Session, User, WeightLog } from "./types"

export const mockUser: User = {
  id: "u_001",
  nameEn: "Ahmed Ahmed",
  nameAr: "أحمد أحمد",
  email: "ahmed@example.com",
  phone: "+971501234567",
  age: 32,
  gender: "male",
  heightCm: 175,
  startWeightKg: 105,
  currentWeightKg: 102.4,
  goal: "lose_weight",
  targetWeightKg: 80,
  activityLevel: "light",
  avatarConfig: {
    bodyMass: 0.85,
    posture: "neutral",
    tone: "soft",
    face: "round",
    skinTone: "#E0B894",
    hairStyle: "short",
    clothing: "sport",
  },
  createdAt: "2026-05-01T00:00:00.000Z",
}

export const mockWeightLogs: WeightLog[] = [
  { id: "w1", date: "2026-06-01", weightKg: 105.0 },
  { id: "w2", date: "2026-06-02", weightKg: 104.6 },
  { id: "w3", date: "2026-06-03", weightKg: 104.4 },
  { id: "w4", date: "2026-06-04", weightKg: 104.0 },
  { id: "w5", date: "2026-06-05", weightKg: 103.8 },
  { id: "w6", date: "2026-06-06", weightKg: 103.5 },
  { id: "w7", date: "2026-06-07", weightKg: 103.2 },
  { id: "w8", date: "2026-06-08", weightKg: 103.1 },
  { id: "w9", date: "2026-06-09", weightKg: 102.8 },
  { id: "w10", date: "2026-06-10", weightKg: 102.6 },
  { id: "w11", date: "2026-06-11", weightKg: 102.4 },
]

export const mockMeals: Meal[] = [
  {
    id: "m1",
    nameEn: "Oats & Berry Bowl",
    nameAr: "شوفان مع التوت",
    descriptionEn: "Steel-cut oats with mixed berries, chia seeds, and almond milk.",
    descriptionAr: "شوفان مع توت مشكل وبذور شيا وحليب لوز.",
    imageUrl: "/meals/oats.jpg",
    calories: 380,
    protein: 14,
    carbs: 58,
    fat: 9,
    mealType: "breakfast",
    tags: ["high-fiber", "vegan", "low-sugar"],
  },
  {
    id: "m2",
    nameEn: "Grilled Chicken Quinoa",
    nameAr: "دجاج مشوي مع كينوا",
    descriptionEn: "Lean chicken breast, quinoa, roasted veggies, lemon-tahini drizzle.",
    descriptionAr: "صدر دجاج مشوي، كينوا، خضار محمصة، صلصة ليمون وطحينة.",
    imageUrl: "/meals/chicken.jpg",
    calories: 520,
    protein: 42,
    carbs: 48,
    fat: 14,
    mealType: "lunch",
    tags: ["high-protein", "gluten-free"],
  },
  {
    id: "m3",
    nameEn: "Baked Salmon & Asparagus",
    nameAr: "سلمون مخبوز مع الهليون",
    descriptionEn: "Wild salmon, roasted asparagus, sweet potato mash.",
    descriptionAr: "سلمون بري، هليون محمص، بطاطا حلوة مهروسة.",
    imageUrl: "/meals/salmon.jpg",
    calories: 610,
    protein: 38,
    carbs: 42,
    fat: 26,
    mealType: "dinner",
    tags: ["omega-3", "low-carb"],
  },
  {
    id: "m4",
    nameEn: "Greek Yogurt & Honey",
    nameAr: "زبادي يوناني مع عسل",
    descriptionEn: "Plain Greek yogurt, raw honey, walnuts.",
    descriptionAr: "زبادي يوناني، عسل نحل طبيعي، عين جمل.",
    imageUrl: "/meals/yogurt.jpg",
    calories: 220,
    protein: 18,
    carbs: 18,
    fat: 9,
    mealType: "snack",
    tags: ["high-protein"],
  },
  {
    id: "m5",
    nameEn: "Lentil Soup",
    nameAr: "شوربة عدس",
    descriptionEn: "Brown lentils, carrots, celery, cumin, lemon.",
    descriptionAr: "عدس بني، جزر، كرفس، كمون، ليمون.",
    imageUrl: "/meals/lentil.jpg",
    calories: 340,
    protein: 22,
    carbs: 48,
    fat: 6,
    mealType: "lunch",
    tags: ["vegan", "high-fiber"],
  },
  {
    id: "m6",
    nameEn: "Egg White Omelette",
    nameAr: "أومليت بياض البيض",
    descriptionEn: "Egg whites, spinach, mushrooms, feta, herbs.",
    descriptionAr: "بياض بيض، سبانخ، فطر، جبنة فيتا، أعشاب.",
    imageUrl: "/meals/omelette.jpg",
    calories: 280,
    protein: 28,
    carbs: 8,
    fat: 14,
    mealType: "breakfast",
    tags: ["high-protein", "keto-friendly"],
  },
]

export const mockProducts: Product[] = [
  {
    id: "p1",
    nameEn: "Almond Energy Bites",
    nameAr: "كُرات اللوز للطاقة",
    descriptionEn: "Gluten-free protein bites. 12g protein per pack.",
    descriptionAr: "كُرات بروتين خالية من الجلوتين. 12جم بروتين للعلبة.",
    imageUrl: "/products/almond-bites.jpg",
    price: 35,
    category: "snack",
    inStock: true,
  },
  {
    id: "p2",
    nameEn: "Detox Green Tea",
    nameAr: "شاي أخضر ديتوكس",
    descriptionEn: "Organic green tea with ginger & lemongrass.",
    descriptionAr: "شاي أخضر عضوي مع الزنجبيل وليمون النجيل.",
    imageUrl: "/products/green-tea.jpg",
    price: 45,
    category: "drink",
    inStock: true,
  },
  {
    id: "p3",
    nameEn: "Vegan Protein Powder",
    nameAr: "بروتين نباتي بودر",
    descriptionEn: "Plant-based protein, chocolate flavor, 1kg.",
    descriptionAr: "بروتين نباتي بنكهة الشوكولاتة، 1 كيلو.",
    imageUrl: "/products/protein.jpg",
    price: 220,
    category: "supplement",
    inStock: true,
  },
  {
    id: "p4",
    nameEn: "Chia Pudding Cup",
    nameAr: "كيك الشيا",
    descriptionEn: "Ready-to-eat chia pudding with mango.",
    descriptionAr: "كيك شيا جاهز للأكل مع المانجو.",
    imageUrl: "/products/chia.jpg",
    price: 28,
    category: "snack",
    inStock: true,
  },
  {
    id: "p5",
    nameEn: "Keto Trail Mix",
    nameAr: "مكس مكسرات كيتو",
    descriptionEn: "Macadamia, pecans, pumpkin seeds, dark chocolate.",
    descriptionAr: "ماكديميا، بيكان، بذور يقطين، شوكولاتة داكنة.",
    imageUrl: "/products/trail-mix.jpg",
    price: 55,
    category: "snack",
    inStock: false,
  },
  {
    id: "p6",
    nameEn: "Daily Multivitamin",
    nameAr: "مالتي فيتامين يومي",
    descriptionEn: "30-day supply, complete micronutrient profile.",
    descriptionAr: "عبوة 30 يوم، عناصر غذائية متكاملة.",
    imageUrl: "/products/multi.jpg",
    price: 120,
    category: "supplement",
    inStock: true,
  },
]

export const mockSessions: Session[] = [
  {
    id: "s1",
    type: "consultation",
    typeEn: "Nutrition Consultation",
    typeAr: "استشارة تغذية",
    doctorName: "Dr. Wael Mostafa",
    date: "2026-06-18",
    time: "10:00",
    durationMinutes: 45,
    status: "scheduled",
    location: "clinic",
    notes: "Bring your food diary.",
  },
  {
    id: "s2",
    type: "body_sculpting",
    typeEn: "Body Sculpting Session",
    typeAr: "جلسة نحت الجسم",
    doctorName: "Dr. Wael Mostafa",
    date: "2026-06-22",
    time: "14:30",
    durationMinutes: 60,
    status: "scheduled",
    location: "clinic",
  },
  {
    id: "s3",
    type: "follow_up",
    typeEn: "Follow-up Check",
    typeAr: "متابعة",
    doctorName: "Dr. Wael Mostafa",
    date: "2026-07-02",
    time: "11:00",
    durationMinutes: 30,
    status: "scheduled",
    location: "online",
  },
  {
    id: "s4",
    type: "consultation",
    typeEn: "Nutrition Consultation",
    typeAr: "استشارة تغذية",
    doctorName: "Dr. Wael Mostafa",
    date: "2026-05-28",
    time: "10:00",
    durationMinutes: 45,
    status: "completed",
    location: "clinic",
  },
]

export const mockDoctorPlan: DoctorPlan = {
  id: "plan_001",
  doctorName: "Dr. Wael Mostafa",
  startDate: "2026-06-01",
  endDate: "2026-08-31",
  goal: "lose_weight",
  notesEn:
    "Cut refined carbs after 4pm. Drink 2.5L water daily. Walk 30 minutes after dinner.",
  notesAr:
    "قلل النشويات بعد الساعة 4 العصر. اشرب 2.5 لتر ميه يومياً. امشي 30 دقيقة بعد العشاء.",
  dailyCalories: 1800,
  waterLiters: 2.5,
  planItems: [
    { id: "pi1", dayOfWeek: 0, meal: mockMeals[5] }, // Sunday breakfast
    { id: "pi2", dayOfWeek: 0, meal: mockMeals[1] }, // Sunday lunch
    { id: "pi3", dayOfWeek: 0, meal: mockMeals[2] }, // Sunday dinner
    { id: "pi4", dayOfWeek: 1, meal: mockMeals[0] },
    { id: "pi5", dayOfWeek: 1, meal: mockMeals[4] },
    { id: "pi6", dayOfWeek: 1, meal: mockMeals[2] },
    { id: "pi7", dayOfWeek: 2, meal: mockMeals[0] },
    { id: "pi8", dayOfWeek: 2, meal: mockMeals[1] },
    { id: "pi9", dayOfWeek: 2, meal: mockMeals[3] },
  ],
}
