"use client"

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { ArrowLeft, Lock, Loader2, Check } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import { useLocale, t } from '@/lib/locale'

// Recovery landing page.
//
// SECURITY MODEL:
//   1. The user arrives here via /auth/confirm after clicking the email link.
//      /auth/confirm created a Supabase session AND set the ldc_recovery_session
//      cookie which the middleware uses to sandbox the user to /reset-password.
//   2. The user picks a new password and submits.
//   3. On success: we clear the recovery cookie, sign the user OUT, and
//      redirect them to /sign-in with a success flash. This is deliberate —
//      the recovery session is provisional and should never be used to
//      actually browse the dashboard or admin. The user must sign in again
//      with the new password.
//
// A legacy fragment-based recovery flow is also supported for users who
// still have a link generated by the old Supabase template (with
// ConfirmationURL).
export default function ResetPasswordPage() {
  const { locale } = useLocale()
  const router = useRouter()

  const [checking, setChecking] = useState(true)
  const [authed, setAuthed] = useState(false)
  const [password, setPassword] = useState('')
  const [confirm, setConfirm] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [done, setDone] = useState(false)

  useEffect(() => {
    const supabase = createClient()

    // Legacy fragment flow: if the URL fragment carries recovery tokens,
    // consume them and call setSession() manually.
    let usedFragment = false
    if (typeof window !== 'undefined' && window.location.hash) {
      const hash = window.location.hash.startsWith('#')
        ? window.location.hash.slice(1)
        : window.location.hash
      const params = new URLSearchParams(hash)
      const access_token = params.get('access_token')
      const refresh_token = params.get('refresh_token')
      const type = params.get('type')
      if (access_token && refresh_token && type === 'recovery') {
        usedFragment = true
        supabase.auth.setSession({ access_token, refresh_token })
          .then(({ data }) => {
            setAuthed(!!data.user)
            setChecking(false)
            // Mark this browser session as a recovery-session so middleware
            // sandboxes it just like the TokenHash flow.
            document.cookie = `ldc_recovery_session=1; Max-Age=600; SameSite=Lax; Secure; Path=/`
            window.history.replaceState(null, '', window.location.pathname)
          })
          .catch(() => { setAuthed(false); setChecking(false) })
      }
    }

    if (usedFragment) return

    // Normal flow: /auth/confirm already set the session cookie via verifyOtp().
    supabase.auth.getUser().then(({ data }) => {
      setAuthed(!!data.user)
      setChecking(false)
    })

    // Belt-and-suspenders for the fragment flow when setSession finishes late.
    const { data: sub } = supabase.auth.onAuthStateChange((event) => {
      if (event === 'PASSWORD_RECOVERY' || event === 'SIGNED_IN') {
        setAuthed(true)
        setChecking(false)
      }
    })
    return () => { sub.subscription.unsubscribe() }
  }, [])

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError('')

    if (password.length < 8) {
      setError(t(locale, 'Password must be at least 8 characters.', 'يجب أن تكون كلمة المرور 8 أحرف على الأقل.'))
      return
    }
    if (password !== confirm) {
      setError(t(locale, 'Passwords do not match.', 'كلمتا المرور غير متطابقتين.'))
      return
    }

    setLoading(true)
    try {
      const supabase = createClient()
      const { error: updErr } = await supabase.auth.updateUser({ password })
      if (updErr) { setError(updErr.message); return }

      // Password saved. Clear the recovery-session marker cookie...
      document.cookie = 'ldc_recovery_session=; Max-Age=0; Path=/; SameSite=Lax'
      // ...and sign the user out. The recovery session is provisional and
      // must not be used to browse further. They will sign back in with
      // the new password.
      await supabase.auth.signOut()

      setDone(true)
      setTimeout(() => {
        router.push('/sign-in?reset=1')
        router.refresh()
      }, 1200)
    } catch {
      setError(t(locale, 'Something went wrong. Please try again.', 'حدث خطأ ما. حاول مرة أخرى.'))
    } finally {
      setLoading(false)
    }
  }

  if (checking) {
    return (
      <main className="flex min-h-screen items-center justify-center">
        <Loader2 className="size-6 animate-spin text-lime-600" />
      </main>
    )
  }

  return (
    <main className="flex min-h-screen items-center justify-center bg-gradient-to-br from-[#f3fae6] to-white px-4">
      <div className="w-full max-w-md rounded-3xl border border-neutral-100 bg-white p-8 shadow-sm">
        <Link href="/sign-in" className="inline-flex items-center gap-1.5 text-sm font-semibold text-neutral-500 hover:text-lime-700">
          <ArrowLeft className="size-4 rtl:rotate-180" /> {t(locale, 'Back to sign in', 'العودة لتسجيل الدخول')}
        </Link>

        <div className="mt-6 flex size-12 items-center justify-center rounded-2xl bg-lime-100 text-lime-700">
          <Lock className="size-6" />
        </div>
        <h1 className="mt-4 text-2xl font-extrabold tracking-tight text-neutral-900">
          {t(locale, 'Choose a new password', 'اختر كلمة مرور جديدة')}
        </h1>

        {!authed ? (
          <div className="mt-6 rounded-2xl bg-amber-50 p-4 text-sm text-amber-800">
            {t(locale,
              "This reset link has expired or is invalid. Request a new one.",
              'انتهت صلاحية هذا الرابط أو أنه غير صالح. اطلب رابطاً جديداً.')}
            <div className="mt-3">
              <Link href="/forgot-password" className="font-semibold text-lime-700 hover:underline">
                {t(locale, 'Request a new link', 'اطلب رابطاً جديداً')}
              </Link>
            </div>
          </div>
        ) : done ? (
          <div className="mt-6 flex items-start gap-3 rounded-2xl bg-lime-50 p-4 text-sm text-lime-800">
            <Check className="mt-0.5 size-5 shrink-0 text-lime-600" />
            <p>{t(locale,
              'Password updated. Redirecting you to sign in with the new password…',
              'تم تحديث كلمة المرور. جارٍ إعادة توجيهك لتسجيل الدخول بكلمة المرور الجديدة…')}</p>
          </div>
        ) : (
          <>
            <p className="mt-3 text-sm text-neutral-500">
              {t(locale,
                'Pick a strong password you have not used before. Minimum 8 characters.',
                'اختر كلمة مرور قوية لم تستخدمها من قبل. 8 أحرف على الأقل.')}
            </p>
            {error && <p className="mt-3 rounded-xl bg-red-50 px-3 py-2 text-sm text-red-600">{error}</p>}
            <form onSubmit={handleSubmit} className="mt-6 space-y-4">
              <div>
                <label className="block text-sm font-semibold text-neutral-700">
                  {t(locale, 'New password', 'كلمة المرور الجديدة')}
                </label>
                <input
                  type="password" required minLength={8}
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder="••••••••"
                  className="mt-1.5 w-full rounded-xl border border-neutral-200 bg-white px-4 py-3 text-sm text-neutral-900 outline-none focus:border-lime-400 focus:ring-2 focus:ring-lime-100"
                />
              </div>
              <div>
                <label className="block text-sm font-semibold text-neutral-700">
                  {t(locale, 'Confirm password', 'تأكيد كلمة المرور')}
                </label>
                <input
                  type="password" required minLength={8}
                  value={confirm}
                  onChange={(e) => setConfirm(e.target.value)}
                  placeholder="••••••••"
                  className="mt-1.5 w-full rounded-xl border border-neutral-200 bg-white px-4 py-3 text-sm text-neutral-900 outline-none focus:border-lime-400 focus:ring-2 focus:ring-lime-100"
                />
              </div>
              <button
                type="submit" disabled={loading}
                className="w-full rounded-xl bg-gradient-to-b from-lime-400 to-lime-500 py-3.5 text-base font-bold text-lime-950 shadow-sm transition hover:-translate-y-0.5 disabled:opacity-60"
              >
                {loading ? t(locale, 'Saving…', 'جارٍ الحفظ…') : t(locale, 'Update password', 'تحديث كلمة المرور')}
              </button>
            </form>
          </>
        )}
      </div>
    </main>
  )
}
