"use client"
import useSWR from "swr"
import { useMemo, useState } from "react"
import { Check, Loader2, RefreshCw, Search, ToggleLeft, ToggleRight } from "lucide-react"

type Resource="services"|"categories"|"bookings"|"reviews"|"gallery"
const fetcher=(url:string)=>fetch(url).then(async r=>{if(!r.ok)throw new Error((await r.json()).error);return r.json()})
const labels:Record<Resource,{title:string;subtitle:string}>={services:{title:"الخدمات",subtitle:"إدارة المحتوى والأسعار والعروض وترتيب الظهور"},categories:{title:"تصنيفات الخدمات",subtitle:"تنظيم الخدمات في مجموعات واضحة"},bookings:{title:"الحجوزات",subtitle:"متابعة الطلبات وتأكيد المواعيد"},reviews:{title:"التقييمات",subtitle:"مراجعة واعتماد آراء العملاء"},gallery:{title:"معرض الخدمات",subtitle:"إدارة الصور وترتيبها في الصفحة العامة"}}
export function BodyModuleManager({resource}:{resource:Resource}){const {data,error,isLoading,mutate}=useSWR(`/api/admin/body-module/${resource}`,fetcher);const [search,setSearch]=useState("");const rows=useMemo(()=>((data?.data??[]) as Record<string,unknown>[]).filter(row=>JSON.stringify(row).toLowerCase().includes(search.toLowerCase())),[data,search]);async function patch(id:unknown,changes:Record<string,unknown>){await fetch(`/api/admin/body-module/${resource}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,...changes})});mutate()}
return <div dir="rtl" className="flex flex-col gap-6"><header><h1 className="text-3xl font-black text-neutral-950">{labels[resource].title}</h1><p className="mt-2 text-neutral-500">{labels[resource].subtitle}</p></header><div className="flex flex-wrap items-center gap-3 rounded-2xl border bg-white p-4"><label className="flex min-h-11 flex-1 items-center gap-2 rounded-xl border px-3"><Search className="size-4 text-neutral-400" /><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث..." className="w-full outline-none" /></label><button onClick={()=>mutate()} className="inline-flex min-h-11 items-center gap-2 rounded-xl border px-4 font-bold"><RefreshCw className="size-4" />تحديث</button></div>{isLoading?<div className="flex min-h-64 items-center justify-center"><Loader2 className="size-8 animate-spin text-emerald-700" /></div>:error?<div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-700">تعذر تحميل البيانات. تأكد من تشغيل ملفات SQL وإعداد Supabase.</div>:rows.length===0?<div className="rounded-2xl border border-dashed bg-white p-12 text-center text-neutral-500">لا توجد بيانات مطابقة.</div>:<div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[760px] text-right text-sm"><thead className="bg-neutral-50 text-neutral-500"><tr><th className="p-4">العنصر</th><th className="p-4">تفاصيل</th><th className="p-4">الحالة</th><th className="p-4">إجراءات سريعة</th></tr></thead><tbody>{rows.map(row=>{const id=String(row.id);const name=String(row.name_ar??row.customer_name??row.title_ar??row.reference??id);const detail=resource==="services"?`${row.price} د.إ • ${row.duration_minutes} دقيقة`:resource==="bookings"?`${row.booking_date} • ${row.booking_time} • ${row.phone}`:resource==="reviews"?`${row.rating}/5 • ${row.comment_ar}`:String(row.slug??row.kind??"");const active=Boolean(row.is_active??row.is_approved??row.status!=="cancelled");return <tr key={id} className="border-t"><td className="p-4 font-bold">{name}</td><td className="max-w-md p-4 text-neutral-500">{detail}</td><td className="p-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${active?"bg-emerald-50 text-emerald-700":"bg-neutral-100 text-neutral-500"}`}>{resource==="bookings"?String(row.status):active?"نشط":"مخفي"}</span></td><td className="p-4">{resource==="bookings"?<button onClick={()=>patch(id,{status:"confirmed"})} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 font-bold"><Check className="size-4" />تأكيد</button>:<button onClick={()=>patch(id,resource==="reviews"?{is_approved:!active}:{is_active:!active})} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 font-bold">{active?<ToggleRight className="size-5"/>:<ToggleLeft className="size-5"/>}{active?"إخفاء":"تفعيل"}</button>}</td></tr>})}</tbody></table></div>}</div>}
