import type { Metadata } from "next"
import Image from "next/image"
import Link from "next/link"
import { notFound } from "next/navigation"
import { ArrowLeft, CheckCircle2, Clock3 } from "lucide-react"
import { BookingForm } from "@/components/body-sculpting/booking-form"
import { fallbackBodyServices, getFallbackService } from "@/lib/body-services"

export function generateStaticParams() { return fallbackBodyServices.map(service => ({ slug: service.slug })) }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const service = getFallbackService(slug); return { title: service ? `${service.nameEn} | ${service.nameAr}` : "Service", description: service?.shortDescriptionEn } }
export default async function ServicePage({ params, searchParams }: { params: Promise<{slug:string}>; searchParams: Promise<{lang?:string}> }) {
  const [{slug},{lang}] = await Promise.all([params,searchParams]); const service=getFallbackService(slug); if(!service) notFound(); const locale=lang==="en"?"en":"ar"; const ar=locale==="ar"; const benefits=ar?service.benefitsAr:service.benefitsEn
  return <main dir={ar?"rtl":"ltr"} className="min-h-screen bg-[#f7f6ef] text-neutral-950"><div className="mx-auto max-w-7xl px-5 py-8 md:px-8"><Link href="/body-sculpting" className="inline-flex items-center gap-2 font-bold text-emerald-900"><ArrowLeft className="size-4 rtl:rotate-180" />{ar?"كل الخدمات":"All services"}</Link><div className="mt-8 grid gap-10 lg:grid-cols-2"><div className="relative aspect-[4/5] overflow-hidden rounded-[2.5rem] bg-neutral-200"><Image src={service.imageUrl} alt={ar?service.nameAr:service.nameEn} fill priority sizes="(max-width:1024px) 100vw,50vw" className="object-cover" /></div><section className="flex flex-col justify-center"><span className="w-fit rounded-full bg-[#d7b56d]/25 px-4 py-2 text-sm font-bold text-emerald-950">{ar?service.badgeAr:service.badgeEn}</span><h1 className="mt-5 text-balance text-4xl font-black sm:text-5xl">{ar?service.nameAr:service.nameEn}</h1><p className="mt-5 text-lg leading-8 text-neutral-600">{ar?service.descriptionAr:service.descriptionEn}</p><div className="mt-6 flex items-center gap-5"><b className="text-3xl text-emerald-900">{service.price} {ar?"د.إ":"AED"}</b>{service.compareAtPrice&&<del className="text-neutral-400">{service.compareAtPrice}</del>}<span className="inline-flex items-center gap-1 text-sm font-bold"><Clock3 className="size-4" />{service.durationMinutes} {ar?"دقيقة":"minutes"}</span></div><ul className="mt-7 grid gap-3 sm:grid-cols-2">{benefits.map(b=><li key={b} className="flex items-start gap-2"><CheckCircle2 className="mt-1 size-5 shrink-0 text-emerald-700" /><span className="leading-7">{b}</span></li>)}</ul><div id="booking" className="mt-10 rounded-[2rem] border border-[#dedacb] bg-white p-6 shadow-sm sm:p-8"><h2 className="text-2xl font-black">{ar?"اطلبي موعدك":"Request an appointment"}</h2><p className="mb-6 mt-2 text-neutral-600">{ar?"املئي البيانات وسيتواصل معك الفريق للتأكيد.":"Complete the form and our team will contact you to confirm."}</p><BookingForm service={service} locale={locale} /></div></section></div></div></main>
}
